[tool.poetry]
name = "codex-tools"
version = "0.1.0"
description = ""
authors = ["Harald Vohringer"]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
xarray = "^2022.6.0"
scikit-image = "^0.19.3"
matplotlib = "^3.5.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
black = "^22.6.0"
isort = "^5.10.1"
flake8 = "^5.0.4"
bandit = "^1.7.4"
safety = "^2.1.1"
pytest-datafiles = "^2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
